# SPDX-License-Identifier: MIT-0
---
- name: Configure bastion server
  hosts: bastion.mementomori.social
  become: true
  roles:
    - common
    - netdata
    - wireguard
  tasks:

    - name: Ensure DNS points here
      community.general.cloudflare_dns:
        zone: mementomori.social
        record: "bastion.mementomori.social"
        type: A
        value: "{{ ansible_facts.eth0.ipv4.address }}"
        solo: true
        proxied: false
        comment: bastion
        api_token: "{{ vault_letsencrypt_cloudflare_api_token }}"
      when: not skip_in_tests | default(false) | bool
