# SPDX-License-Identifier: MIT-0
---
- name: Configure mastodon host
  hosts: mastodon-0.mementomori.social
  become: true
  roles:
    - common
    - netdata
    - valkey
    - role: nginx_mementomori
      vars:
        nginx_disable_all: true
    - role: mastodon
      vars:
        mastodon_disable_all: true
