# SPDX-License-Identifier: MIT-0
---
- ansible.builtin.import_playbook: ./bastion.mementomori.social.yml
- ansible.builtin.import_playbook: ./postgresql.mementomori.social.yml
- ansible.builtin.import_playbook: ./elastic.mementomori.social.yml
- ansible.builtin.import_playbook: ./mastodon-0.mementomori.social.yml
