# SPDX-License-Identifier: MIT-0
---
- name: Create UpCloud postgresql host
  hosts: localhost
  connection: local
  vars:
    upcloud_token: "{{ vault_upcloud_ansible_token }}"
    upcloud_api_url: "https://api.upcloud.com/1.3"
    zone: "fi-hel2"
    server_hostname: "postgresql.mementomori.social"
    server_title: "Database Server"
    server_plan: "CLOUDNATIVE-6xCPU-24GB"
    source_storage_uuid: "01000000-0000-4000-8000-000030260200"
    storage_size_root: 30
    # Created beforehand with upctl storage create, see README
    data_storage_uuid: "019c8a81-8435-44df-a867-ebbac33a9443"
    backup_storage_uuid: "018b7d80-3da9-4f08-89a7-ac87b363f1a6"
    network_name: "fi-hel2-mastodon-network"
    server_ip: 10.222.222.13
    labels:
      - key: role
        value: postgresql

  tasks:
    - name: Fetch networks from upcloud
      ansible.builtin.uri:
        url: "{{ upcloud_api_url }}/network"
        method: GET
        headers:
          Authorization: "Bearer {{ upcloud_token }}"
      register: upcloud_networks_response
      no_log: true

    - name: Find network UUID by name
      ansible.builtin.set_fact:
        mastodon_network:
          "{{ (upcloud_networks_response.json.networks.network | selectattr('name', 'equalto', network_name) | first) }}"

    - name: Display network info
      ansible.builtin.debug:
        msg: "Network {{ mastodon_network.name }} has UUID {{ mastodon_network.uuid }}"

    - name: Create UpCloud server
      ansible.builtin.uri:
        url: "{{ upcloud_api_url }}/server"
        method: POST
        headers:
          Authorization: "Bearer {{ upcloud_token }}"
        body_format: json
        body:
          server:
            hostname: "{{ server_hostname }}"
            title: "{{ server_title }}"
            zone: "{{ zone }}"
            plan: "{{ server_plan }}"
            metadata: 'yes'
            # firewall: ''
            storage_devices:
              storage_device:
                - title: "{{ server_hostname }}-rootdisk"
                  action: clone
                  storage: "{{ source_storage_uuid }}"
                  tier: "standard"
                  size: "{{ storage_size_root }}"
                - action: attach
                  storage: "{{ data_storage_uuid }}"
                - action: attach
                  storage: "{{ backup_storage_uuid }}"
            networking:
              interfaces:
                interface:
                  - type: private
                    source_ip_filtering: 'no'
                    network: "{{ mastodon_network.uuid }}"
                    bootable: 'no'
                    ip_addresses:
                      ip_address:
                        - address: "{{ server_ip }}"
                          family: IPv4
                          dhcp_provided: 'yes'
            nic_model: virtio
            password_delivery: 'none'
            timezone: "Europe/Helsinki"
            labels:
              label: "{{ labels }}"
            login_user:
              username: ansible
              ssh_keys:
                # yamllint disable-line rule:line-length
                ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHzXEq5NVyJPgrnfdVFJPpb9OPE5O4P9mkZjU2m4h08iV9/7isc2AeKL5y8qq2o3JNAx6UxL6Pw4daaDEnHE6jyEhPKW3nbfR+trO1bPVa3URFWTdn+lpaggJjs195rF0u9WZD2WP/PwuWFB6mhG4aFoxsGn9phFowY9walGNVJuR1eSfVwAMnY9ehO/XWwUui7xyWeaNahOzxO9OrimpmwOxc9LH6KoBOuxcDh/Q/O7SEhin9papgAd/QgFdLuzvlwvEkXjIllA+xb4QHg19EBkH66NFEDlnrs8obYCYj0MN/LuSr1ag+u0yBIHfq4S+7hQhdszybPjZujSTQo7f0UazStnDsB8CQFFxyJzPZFXrmptqe9J+mQBYdEx815pDcaiy4CpwcNlWk+4jWTQRGOviQZTHMXNHofjwLqVug4NvJaDPzYJwuIJVXRNypwx/9sbLroReCp3S2vILzsUiSL/FQOZgfvycDkwFRbzZZoz7XbKf/QvxG7PCgJznD423O3pSKgh3iSznxlMpPgtP6/cJVrFVEdKxcgz891wQ0XhUfzDPUoI5boCt9OVojIH6WOa3u1mok0ePtb9Q53Ai6gT2GkzsKKXy7T7c5VHVnSiUvXxYB+2zUL8l0LFWbfeOV1WWkA1HikHOm50nTEFht7xPu5iyqUY1n1E8UrI3iIw==
              create_password: 'no'
        status_code: 202
      register: upcloud_server_response

    - name: Debug the return code
      ansible.builtin.debug:
        var: upcloud_server_response

    - name: Set fact with created server details
      ansible.builtin.set_fact:
        upcloud_server: "{{ upcloud_server_response.json.server }}"
        upcloud_server_uuid: "{{ upcloud_server_response.json.server.uuid }}"
        upcloud_server_state: "{{ upcloud_server_response.json.server.state }}"

  post_tasks:
    - name: Display created server info
      ansible.builtin.debug:
        msg:
          - "Server UUID: {{ upcloud_server_uuid }}"
          - "Server Title: {{ upcloud_server.title }}"
          - "Server Hostname: {{ upcloud_server.hostname }}"
          - "Server Zone: {{ upcloud_server.zone }}"
          - "Server State: {{ upcloud_server_state }}"
          - "Server Plan: {{ upcloud_server.plan }}"
          - "Attached Network: {{ mastodon_network.name }} ({{ mastodon_network.uuid }})"
