# SPDX-License-Identifier: MIT-0
---
# handlers file for elasticsearch

- name: Restart elasticsearch
  ansible.builtin.service:
    name: "{{ elasticsearch_service }}"
    state: restarted
  when: not skip_in_tests

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
