# SPDX-License-Identifier: MIT-0
---
- name: Install valkey
  block:
    - name: Ensure valkey is installed
      ansible.builtin.apt:
        name:
          - valkey-server
          - valkey-tools
        state: present
        update_cache: true

    - name: Ensure valkey service is enabled and started
      ansible.builtin.service:
        name: valkey-server
        state: started
        enabled: true

  rescue:
    - name: Report failure
      ansible.builtin.fail:
        msg: "Failed to install and configure valkey"
