---
- name: Verify common
  hosts: all
  gather_facts: true
  vars:
    skip_in_tests: true
  tasks:
    - name: Check required packages are installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify python3 is installed
      ansible.builtin.assert:
        that:
          - "'python3' in ansible_facts.packages"
        fail_msg: "Python3 package not found"

    - name: Verify systemd service is running
      ansible.builtin.systemd:
        name: systemd-logind
        state: started
      check_mode: true
      register: systemd_check
      failed_when: false

    - name: Assert systemd is active
      ansible.builtin.assert:
        that:
          - systemd_check is not failed
        fail_msg: "Systemd service not running"

    - name: Verify users created
      ansible.builtin.user:
        name: ikke
        state: present
      check_mode: true
      register: user_check
      failed_when: false

    - name: Assert users created
      ansible.builtin.assert:
        that:
          - user_check is not failed
        fail_msg: "User missing"

    - name: Verify users has ssh pubkey
      ansible.builtin.stat:
        path: /home/ikke/.ssh/authorized_keys
      register: ak

    - name: Assert authorized keys created
      ansible.builtin.assert:
        that:
          - ak.stat.isreg is not false
        fail_msg: "Authorized_keys missing"

    - name: Verify SSH option
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regex: 'PasswordAuthentication no'
      check_mode: true
      register: ssh_opt_check
      failed_when: false

    - name: Assert users created
      ansible.builtin.assert:
        that:
          - ssh_opt_check is not failed
        fail_msg: "SSH option missing"

- name: Verify postgresql
  hosts: postgresql
  gather_facts: true
  vars:
    skip_in_tests: true
    postgresql_version: 17
  tasks:

    - name: Symlink for persistent data exists
      ansible.builtin.stat:
        path: /var/lib/postgresql/{{ postgresql_version }}/main
      register: postgresql_link

    - name: Assert postgresql persistent data dir is linked
      ansible.builtin.assert:
        that:
          - postgresql_link.stat.islnk is defined
          - postgresql_link.stat.islnk
        fail_msg: "postgresql link missing"

    - name: Verify postgresql service is running
      ansible.builtin.systemd:
        name: postgresql
        state: started
      check_mode: true
      register: postgresql_check
      failed_when: false

    - name: Assert postgresql
      ansible.builtin.assert:
        that:
          - postgresql_check is started
        fail_msg: "Postgresql is not running"

- name: Verify valkey
  hosts: valkey
  gather_facts: true
  vars:
    skip_in_tests: true
  tasks:
    - name: Check required packages are installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify valkey-server is installed
      ansible.builtin.assert:
        that:
          - "'valkey-server' in ansible_facts.packages"
        fail_msg: "valkey-server package not found"

    - name: Verify valkey service is running
      ansible.builtin.systemd:
        name: valkey-server
        state: started
      check_mode: true
      register: valkey_check
      failed_when: false

    - name: Assert valkey
      ansible.builtin.assert:
        that:
          - valkey_check is started
        fail_msg: "Valkey is not running"
