# SPDX-License-Identifier: MIT-0
---

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart mastodon services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ mastodon_services }}"
  when: not skip_in_tests

- name: Stop mastodon services for migration
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ mastodon_services }}"
  when: not skip_in_tests and item is search('sidekiq')
