# SPDX-License-Identifier: MIT-0
---

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart mastodon services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ mastodon_services }}"
  when: skip_in_tests is not defined or not mastodon_disable_all
