# SPDX-License-Identifier: MIT-0
---
- name: Restart valkey
  ansible.builtin.service:
    name: valkey-server
    state: restarted

- name: Reload valkey
  ansible.builtin.service:
    name: valkey-server
    state: reloaded
