# SPDX-License-Identifier: MIT-0
---

mastodon_data_device: /dev/sdb
mastodon_data_mountpoint: /data
mastodon_mount_fs_type: ext4
mastodon_mount_opts: defaults
mastodon_home: "{{ mastodon_data_mountpoint }}/mastodon"

mastodon_packages:
  - autoconf
  - bison
  - build-essential
  - curl
  - ffmpeg
  - file
  - git
  - imagemagick
  - libffi-dev
  - libgdbm-dev
  - libicu-dev
  - libidn-dev
  - libjemalloc-dev
  - libpq-dev
  - libreadline-dev
  - libssl-dev
  - libvips-tools
  - libxslt1-dev
  - libyaml-dev
  - nodejs
  - pkg-config
  - protobuf-compiler
  - wget
  - zlib1g-dev

mastodon_systemd_files:
  - mastodon-sidekiq-1-default@.service
  - mastodon-sidekiq-1-ingress@.service
  - mastodon-sidekiq-2-default@.service
  - mastodon-sidekiq-2-ingress@.service
  - mastodon-sidekiq-default@.service
  - mastodon-sidekiq-fasp@.service
  - mastodon-sidekiq-ingress@.service
  - mastodon-sidekiq-mailers@.service
  - mastodon-sidekiq-pull@.service
  - mastodon-sidekiq-push@.service
  - mastodon-sidekiq-scheduler@.service
  - mastodon-sidekiq.service
  - mastodon-sidekiq-template.service
  - mastodon-streaming.service
  - mastodon-streaming@.service
  - mastodon-web.service
  # timers
  - mastodon-media-clear.service
  - mastodon-media-clear.timer
  - mastodon-prune.service
  - mastodon-prune.timer
  - mastodon-sidekiq-check.service
  - mastodon-sidekiq-check.timer
  - mastodon-build-search-index.service
  - mastodon-build-search-index.timer
  - mastodon-flush-dead-jobs.service
  - mastodon-flush-dead-jobs.timer
  - mastodon-fedifetcher.service
  - mastodon-fedifetcher.timer
  - mastodon-refetch-preview-cards.service
  - mastodon-refetch-preview-cards.timer

# XXX The following list has such entries commented out which existed on the
# old server, but were not enabled. Do we need them anymore?
mastodon_services:
  # - mastodon-fasp.service
  # - mastodon-sidekiq-default.service
  # - mastodon-sidekiq-default@.service
  # - mastodon-sidekiq-default@20.service
  # - mastodon-sidekiq-default@40.service
  # - mastodon-sidekiq-1-default@25.service
  - mastodon-sidekiq-1-default@35.service
  # - mastodon-sidekiq-1-default@40.service
  - mastodon-sidekiq-1-ingress@25.service
  # - mastodon-sidekiq-2-default@25.service
  - mastodon-sidekiq-2-default@35.service
  # - mastodon-sidekiq-2-default@40.service
  # - mastodon-sidekiq-2-default@60.service
  - mastodon-sidekiq-2-ingress@25.service
  - mastodon-sidekiq-fasp@1.service
  # - mastodon-sidekiq-ingress@.service
  # - mastodon-sidekiq-mailer@20.service
  # - mastodon-sidekiq-mailers@.service
  - mastodon-sidekiq-mailers@20.service
  # - mastodon-sidekiq-pull@.service
  - mastodon-sidekiq-pull@40.service
  # - mastodon-sidekiq-push@.service
  - mastodon-sidekiq-push@35.service
  # - mastodon-sidekiq-scheduler@.service
  - mastodon-sidekiq-scheduler@5.service
  # - mastodon-sidekiq.service
  - mastodon-streaming.service
  - mastodon-streaming@4000.service
  - mastodon-streaming@4001.service
  - mastodon-streaming@4002.service
  - mastodon-streaming@4003.service
  - mastodon-web.service
  # timers
  - mastodon-media-clear.timer
  - mastodon-prune.timer
  - mastodon-sidekiq-check.timer
  - mastodon-build-search-index.timer
  - mastodon-flush-dead-jobs.timer
  - mastodon-fedifetcher.timer
  - mastodon-refetch-preview-cards.timer

mastodon_fedifetch_access_token: "{{ vault_mastodon_fedifetch_access_token }}"
mastodon_fedifetch_server: mementomori.social
mastodon_betterstack_sidekick: "{{ vault_mastodon_betterstack_sidekick }}"
