galaxy_info:
  author: ilkka.tengvall@iki.fi
  description: administrator
  company: Mementomori RY
  issue_tracker_url: https://github.com/mementomori-social/ansibles/issues
  license: BSD-3-Clause
  min_ansible_version: 2.2
  galaxy_tags: []
dependencies: []
