#SPDX-License-Identifier: MIT-0
---
- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
  when:
    - not nginx_disable_all

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
